### ISSUE TITLE
拉勾最新版本应该接入的是阿里的sdk，你这个关键部分还是用sdk获取视频地址的？但是不适用所有阿里sdk的加密？

### ISSUE THREAD

**Issue by lidiwo** [SweetInk/lagou-course-downloader#10]
极客时间的视频也是接入阿里云sdk，但是人家视频是经过加密的，通过sdk 获取播放信息，获取的播放地址也是m3u8，是加密的，关键是解密m3u8 里面的key 信息，才可以解密视频，一旦拉勾的视频也采用AliyunVoDEncryption 加密，通过获取视频信息获取到的地址不是mp4格式，这个就下载不了

**Comment by SweetInk** [comment]
极客时间的没研究过，拉钩的通过解密可以获取到mp4地址（最近没试过）

**Comment by SweetInk** [comment]
加密算法我已经分析出来了，还得分析`ts`文件，它不是整个文件都加密，而是把ts文件中的视频、音频数据加密了。

**Comment by EvanZhou666** [comment]
> 极客时间的没研究过，拉钩的通过解密可以获取到mp4地址



> 加密算法我已经分析出来了，还得分析`ts`文件，它不是整个文件都加密，而是把ts文件中的视频、音频数据加密了。

请问这种要怎么分析，能提供一些思路吗，最近在研究极客的，m3u8中的URI被加密处理过了。
![image](https://user-images.githubusercontent.com/34089714/144370329-61d28afa-2b6d-46b8-8495-eef678d895e7.png)

**Comment by SweetInk** [comment]
> 请问这种要怎么分析，能提供一些思路吗，最近在研究极客的，m3u8中的URI被加密处理过了。

可以考虑从他们的web端的js player分析入手
