### ISSUE TITLE
运行如下错误，该怎么解决呢

### ISSUE THREAD

**Issue by UIT2016wanghui** [SweetInk/lagou-course-downloader#12]
[INFO ] 2020-12-08 20:35:21.492 [main] [online.githuboy.lagou.course.Downloader] - 检查ffmpeg是否存在
[ERROR] 2020-12-08 20:35:21.516 [main] [online.githuboy.lagou.course.Downloader] - Cannot run program "ffmpeg" (in directory "."): CreateProcess error=2, 系统找不到指定的文件。

**Comment by SweetInk** [comment]
安装`ffmpeg`，然后配置`ffmpeg.exe`路径到`PATH`环境变量
