### ISSUE TITLE
直接运行会出现大量的Timeout，其实分析出mp4地址后，可以用wget来下载呀，设置断点续传参数

### ISSUE THREAD

**Issue by k7gxn56** [SweetInk/lagou-course-downloader#15]
会出现

Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly

cn.hutool.core.io.IORuntimeException: SocketTimeoutException: connect timed out

应该可以多线程调用wget去下载分析出来的mp4地址

**Comment by SweetInk** [comment]
用`wget`确实不错的主意，刚才试了下
