### ISSUE TITLE
CmdExecutor用到了一个类PublicUtils却在代码和依赖中没有

### ISSUE THREAD

**Issue by donald001** [SweetInk/lagou-course-downloader#2]
CmdExecutor用到了一个类`import online.githuboy.lagou.course.utils.PublicUtils;`却在代码和依赖中没有， 是不是您忘传了？

**Comment by donald001** [comment]
在VideoInfoLoader中也有一个`import online.githuboy.lagou.course.utils.HttpUtils;` 您忘传了。

**Comment by SweetInk** [comment]
我检查下
