### ISSUE TITLE
阿里云的hls解密，可以出个教程吗

### ISSUE THREAD

**Issue by yh371174229** [SweetInk/lagou-course-downloader#28]
阿里云的hls解密，可以出个教程吗

**Comment by SweetInk** [comment]
后面有时间更新到blog上，你可以看下代码[TSParser.java](https://github.com/SweetInk/lagou-course-downloader/blob/master/src/main/java/online/githuboy/lagou/course/decrypt/alibaba/TSParser.java)

**Comment by yh371174229** [comment]
我看看吧，感谢大佬的指导
