### ISSUE TITLE
getkey获取不到

### ISSUE THREAD

**Issue by LiShang007** [SweetInk/lagou-course-downloader#29]
![image](https://user-images.githubusercontent.com/8901724/122748148-7399a380-d2be-11eb-86e1-916c51986578.png)
为何过滤不到getkey

**Comment by SweetInk** [comment]
getkey是什么？

**Comment by LiShang007** [comment]
搞错了，我以为cookies是需要使用getkey那个url下的cookies 。现在已经可以下载，但是为何下载的视频都是几kb的无法观看
![image](https://user-images.githubusercontent.com/8901724/122853620-185ec400-d345-11eb-92db-222627b5dfac.png)

**Comment by LiShang007** [comment]
拉取最新代码可以了，谢谢
