### ISSUE TITLE
请问如何下载训练营的课程？

### ISSUE THREAD

**Issue by sickfun** [SweetInk/lagou-course-downloader#38]
课程ID好像不是一个体系，请问应该如何找到正确的ID？
![image](https://user-images.githubusercontent.com/88948550/129459932-a6036796-95f4-4340-85a5-13334e5b2f56.png)
![image](https://user-images.githubusercontent.com/88948550/129459967-1814b396-5981-425a-ab4e-870c7656fb56.png)

**Comment by SweetInk** [comment]
没训练营课程，自行分析。

**Comment by sickfun** [comment]
OK 了，只要运行 `App_XunLianYing.main()` 即可

**Comment by robertdeng1212** [comment]
> OK 了，只要运行 `App_XunLianYing.main()` 即可
![image](https://user-images.githubusercontent.com/31593084/185374139-9cf2b551-113a-4b3b-864e-869def9244fc.png)


你好，我也在下载和你同系列的课程，请问你全部下载下来了吗？我只下了文件目录，视频没下载成功
