### ISSUE TITLE
可以详细讲解一下怎么运行么？

### ISSUE THREAD

**Issue by LuckyMango** [SweetInk/lagou-course-downloader#4]
我将代码下载下来以后不知道该怎么运行，方便告知一下么？

**Comment by loaderlin** [comment]
1. 要在Window环境下载 ffmpeg 软件 并加入环境变量
参考链接 [How to Install FFmpeg on Windows](http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/)
2. 下载源码 并用IDEA打开
3.  修改CookieStore类的cookie变量；Downloader类中的main方法的courseId（课程Id）和savePath（本地保存地址），运行main方法即可
