### ISSUE TITLE
Training camp download error

### ISSUE THREAD

**Issue by cy920820** [SweetInk/lagou-course-downloader#50]
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/21211512/153455953-a93325a0-e892-4f67-ad27-62a135299669.png">

**Comment by cy920820** [comment]
我看到本地的初始目录是创建出来了

<img width="720" alt="image" src="https://user-images.githubusercontent.com/21211512/153458315-b96b42eb-06e9-4a0d-b84b-a96f7ce63442.png">

**Comment by SweetInk** [comment]
我没有训练营课程，没法测试

**Comment by Zhang-Chong** [comment]
> 非训练营的课程能够正常下载

我可以代大佬远程给你解决 需要的话加我 ZhangchongSR0208
