### ISSUE TITLE
大佬 可以要您一个联系方式嘛

### ISSUE THREAD

**Issue by JamesGosl** [SweetInk/lagou-course-downloader#51]
在大佬的代码里 核心的就是那个AliyunApiUtils 类，希望能和大佬交流，必有重谢

ZhangchongSR0208 我微信 大佬如果没有时间回复的话 加我一下也行，必有重谢

**Comment by lbbniu** [comment]
> 在大佬的代码里 核心的就是那个AliyunApiUtils 类，希望能和大佬交流，必有重谢
> 
> ZhangchongSR0208 我微信 大佬如果没有时间回复的话 加我一下也行，必有重谢

go 版本，欢迎交流 https://github.com/lbbniu/aliyun-m3u8-downloader
