### ISSUE TITLE
问题很多...

### ISSUE THREAD

**Issue by ijrou** [SweetInk/lagou-course-downloader#7]
俺java小白，用eclipse jdk1.8编译，可否告知大人用了jdk几，发现几处问题：

1、大佬尝试用 `String.format(“{0}”, courseId);` ,但是发现行不通，需要修改为： `MessageFormat.format(“{0}”, courseId);`，在  "Downloader.java" 构造函数中

2、下载时大佬使用标题来作为视频文件名，但是标题一般有非法存在（针对window），没有做文件名过滤处理，需要如下：

```java
import java.util.regex.Pattern;

Pattern FilePattern = Pattern.compile("[\\\\/:*?\"<>|]");        
videoName = videoName==null?null:FilePattern.matcher(videoName).replaceAll("");
```

3、存在 “获取媒体信息失败”，在 "MP4Downloader.java" 中，但是应该不影响..(没细看)

我一个NET看Java代码，就下载IDE配置JDK各种骚操作才运行起来。。。心累啊。。。

**Comment by SweetInk** [comment]
上面问题解决了...
